# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: pytest

on:
  # Trigger the workflow on push to main or any pull request
  push:
    branches: ["main", "develop"]
  pull_request:
    types: ["opened", "synchronize"]

jobs:
  main:
    strategy:
      matrix:
        platform: ["ubuntu-latest"]
        python-version: ["3.11", "3.12", "3.13"]
        pytest_marker:
          - null
          # - "retriever_dual_encoder"
          # - "retriever_text_embedding"
          # - "retriever_bm25"
          # - "retriever_e5bm25"
          # - "reranker_fevry"
          # - "reranker_blink"
          # - "reranker_chatel"
          # - "reranker_fusioned"
          # - "reranker_extend"

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v6
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install
    - name: Install the project
      run: uv sync --all-extras --dev --index torch=https://download.pytorch.org/whl/cpu --index-strategy unsafe-best-match
    - name: Install pip for spaCy
      run: uv pip install pip
    - name: Download spaCy model
      run: uv run -- spacy download en_core_web_sm
    - name: Test with pytest
      run: |
        uv run pytest ${{ matrix.pytest_marker && format('-m {0}', matrix.pytest_marker) || '' }}
